CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    ts DOUBLE PRECISION NOT NULL,
    ip VARCHAR(255) NOT NULL,
    data TEXT NOT NULL
);
