name: Frontend Linter Check

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Switch to web directory
        run: cd web
      - name: Install packages
        run: npm install
      - name: Run ESLint
        run: npm run lint
